# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/

baseurl = "/"

title = "Bas Nijholt"

copyright = "&copy; 2018"  # appears in site footer.

theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10

disqusShortname = ""

googleAnalytics = ""

defaultContentLanguage = "en"
hasCJKLanguage = false
defaultContentLanguageInSubdir = false

# Get last modified date for content from Git?
enableGitInfo = true

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

[blackfriday]
  hrefTargetBlank = true
  fractions = true
  smartypants = true

[params]
  color_theme = "default"

  font = "classic"

  name = "Bas Nijholt"
  role = "Ph.D. candidate"

  organizations = [ { name = "TU Delft", url = "https://quantumtinkerer.tudelft.nl/" } ]

  gravatar = true
  avatar = "portrait.jpg"
  email = "bas@nijho.lt"
  address = "Building 22 Room F329, TU Delft, Lorentzweg 1, Delft, 2628 CJ, NLD"
  phone = "+31613049138"
  skype = "basnijholt"
  telegram = "basnijholt"

  # Enable Keybase in Contact widget by entering your keybase.io username.
  keybase = ""

  # Diplay a logo in navigation bar rather than title (optional).
  #   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
  logo = ""

  map = 2
  map_api_key = ""
  latitude = "51.991003"
  longitude = "4.380039"
  zoom = 4

  date_format = "Jan 2, 2006"
  time_format = "15:04"

  reading_time = true

  comment_count = true

  section_pager = false

  math = true

  highlight = true
  highlight_languages = ["python"]
  highlight_style = "github"

  sharing = true

  privacy_pack = false

  custom_css = []
  custom_js  = []

  publication_types = [
    'Preprint',  # 0
    'Journal article',  # 1
  ]

  [params.talks]
    time = true  # Show talk time?

  [params.publications]
    date_format = "January, 2006"

  [params.projects]
    list_children = true
    publication_format = 3

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:bas@nijho.lt"

  [[params.social]]
    icon = "instagram"
    icon_pack = "fa"
    link = "//instagram.com/bnijholt"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=nIO4EK4AAAAJ&hl"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/basnijholt"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "https://www.linkedin.com/in/basnijholt"

  [params.menus]
    align_right = true

    [[menu.main]]
      name = "Home"
      url = "#about"
      weight = 1

    [[menu.main]]
      name = "Publications"
      url = "#publications"
      weight = 2

    [[menu.main]]
      name = "Projects"
      url = "#projects"
      weight = 4

    [[menu.main]]
      name = "Photography"
      url = "#photography"
      weight = 5

    [[menu.main]]
      name = "Contact"
      url = "#contact"
      weight = 6

[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

[Languages.en]
  languageCode = "en-us"
